"""Emission compliance tests for assessor (auto-generated by pact)."""

from assessor.assessor import Assessor


class TestEmissionCompliance:
    """Verify assessor emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_merge_assessments_emits_events(self):
        """Method merge_assessments emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Assessor(event_handler=handler)
        try:
            obj.merge_assessments()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for merge_assessments'
        assert len(completed) >= 1, 'No completed/error event for merge_assessments'
        assert invoked[0].get("pact_key") == "PACT:assessor:merge_assessments"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test__resolve_trust_emits_events(self):
        """Method _resolve_trust emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Assessor(event_handler=handler)
        try:
            obj._resolve_trust()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for _resolve_trust'
        assert len(completed) >= 1, 'No completed/error event for _resolve_trust'
        assert invoked[0].get("pact_key") == "PACT:assessor:_resolve_trust"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test__deduplicate_findings_emits_events(self):
        """Method _deduplicate_findings emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Assessor(event_handler=handler)
        try:
            obj._deduplicate_findings()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for _deduplicate_findings'
        assert len(completed) >= 1, 'No completed/error event for _deduplicate_findings'
        assert invoked[0].get("pact_key") == "PACT:assessor:_deduplicate_findings"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test__compute_decision_emits_events(self):
        """Method _compute_decision emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Assessor(event_handler=handler)
        try:
            obj._compute_decision()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for _compute_decision'
        assert len(completed) >= 1, 'No completed/error event for _compute_decision'
        assert invoked[0].get("pact_key") == "PACT:assessor:_compute_decision"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test__build_report_emits_events(self):
        """Method _build_report emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Assessor(event_handler=handler)
        try:
            obj._build_report()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for _build_report'
        assert len(completed) >= 1, 'No completed/error event for _build_report'
        assert invoked[0].get("pact_key") == "PACT:assessor:_build_report"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Assessor(event_handler=handler)
        try:
            obj.merge_assessments()
        except (TypeError, Exception):
            pass
        try:
            obj._resolve_trust()
        except (TypeError, Exception):
            pass
        try:
            obj._deduplicate_findings()
        except (TypeError, Exception):
            pass
        try:
            obj._compute_decision()
        except (TypeError, Exception):
            pass
        try:
            obj._build_report()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:assessor:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Assessor()
        try:
            obj.merge_assessments()
        except (TypeError, Exception):
            pass
        try:
            obj._resolve_trust()
        except (TypeError, Exception):
            pass
        try:
            obj._deduplicate_findings()
        except (TypeError, Exception):
            pass
        try:
            obj._compute_decision()
        except (TypeError, Exception):
            pass
        try:
            obj._build_report()
        except (TypeError, Exception):
            pass
