"""Emission compliance tests for circuit (auto-generated by pact)."""

from circuit.circuit import Circuit


class TestEmissionCompliance:
    """Verify circuit emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test___init___emits_events(self):
        """Method __init__ emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Circuit(event_handler=handler)
        try:
            obj.__init__()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for __init__'
        assert len(completed) >= 1, 'No completed/error event for __init__'
        assert invoked[0].get("pact_key") == "PACT:circuit:__init__"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_run_emits_events(self):
        """Method run emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Circuit(event_handler=handler)
        try:
            obj.run()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for run'
        assert len(completed) >= 1, 'No completed/error event for run'
        assert invoked[0].get("pact_key") == "PACT:circuit:run"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_resolve_execution_plan_emits_events(self):
        """Method resolve_execution_plan emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Circuit(event_handler=handler)
        try:
            obj.resolve_execution_plan()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for resolve_execution_plan'
        assert len(completed) >= 1, 'No completed/error event for resolve_execution_plan'
        assert invoked[0].get("pact_key") == "PACT:circuit:resolve_execution_plan"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_invoke_reviewer_emits_events(self):
        """Method invoke_reviewer emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Circuit(event_handler=handler)
        try:
            obj.invoke_reviewer()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for invoke_reviewer'
        assert len(completed) >= 1, 'No completed/error event for invoke_reviewer'
        assert invoked[0].get("pact_key") == "PACT:circuit:invoke_reviewer"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_get_stage_timeout_emits_events(self):
        """Method get_stage_timeout emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Circuit(event_handler=handler)
        try:
            obj.get_stage_timeout()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for get_stage_timeout'
        assert len(completed) >= 1, 'No completed/error event for get_stage_timeout'
        assert invoked[0].get("pact_key") == "PACT:circuit:get_stage_timeout"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_get_execution_plan_emits_events(self):
        """Method get_execution_plan emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Circuit(event_handler=handler)
        try:
            obj.get_execution_plan()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for get_execution_plan'
        assert len(completed) >= 1, 'No completed/error event for get_execution_plan'
        assert invoked[0].get("pact_key") == "PACT:circuit:get_execution_plan"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Circuit(event_handler=handler)
        try:
            obj.__init__()
        except (TypeError, Exception):
            pass
        try:
            obj.run()
        except (TypeError, Exception):
            pass
        try:
            obj.resolve_execution_plan()
        except (TypeError, Exception):
            pass
        try:
            obj.invoke_reviewer()
        except (TypeError, Exception):
            pass
        try:
            obj.get_stage_timeout()
        except (TypeError, Exception):
            pass
        try:
            obj.get_execution_plan()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:circuit:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Circuit()
        try:
            obj.__init__()
        except (TypeError, Exception):
            pass
        try:
            obj.run()
        except (TypeError, Exception):
            pass
        try:
            obj.resolve_execution_plan()
        except (TypeError, Exception):
            pass
        try:
            obj.invoke_reviewer()
        except (TypeError, Exception):
            pass
        try:
            obj.get_stage_timeout()
        except (TypeError, Exception):
            pass
        try:
            obj.get_execution_plan()
        except (TypeError, Exception):
            pass
