"""Emission compliance tests for mcp_server (auto-generated by pact)."""

from mcp_server.mcp_server import McpServer


class TestEmissionCompliance:
    """Verify mcp_server emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_create_server_emits_events(self):
        """Method create_server emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.create_server()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for create_server'
        assert len(completed) >= 1, 'No completed/error event for create_server'
        assert invoked[0].get("pact_key") == "PACT:mcp_server:create_server"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_run_server_emits_events(self):
        """Method run_server emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.run_server()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for run_server'
        assert len(completed) >= 1, 'No completed/error event for run_server'
        assert invoked[0].get("pact_key") == "PACT:mcp_server:run_server"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_handle_review_emits_events(self):
        """Method handle_review emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.handle_review()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for handle_review'
        assert len(completed) >= 1, 'No completed/error event for handle_review'
        assert invoked[0].get("pact_key") == "PACT:mcp_server:handle_review"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_handle_trust_emits_events(self):
        """Method handle_trust emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.handle_trust()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for handle_trust'
        assert len(completed) >= 1, 'No completed/error event for handle_trust'
        assert invoked[0].get("pact_key") == "PACT:mcp_server:handle_trust"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_handle_history_emits_events(self):
        """Method handle_history emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.handle_history()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for handle_history'
        assert len(completed) >= 1, 'No completed/error event for handle_history'
        assert invoked[0].get("pact_key") == "PACT:mcp_server:handle_history"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_build_tool_error_emits_events(self):
        """Method build_tool_error emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.build_tool_error()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for build_tool_error'
        assert len(completed) >= 1, 'No completed/error event for build_tool_error'
        assert invoked[0].get("pact_key") == "PACT:mcp_server:build_tool_error"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_build_success_result_emits_events(self):
        """Method build_success_result emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.build_success_result()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for build_success_result'
        assert len(completed) >= 1, 'No completed/error event for build_success_result'
        assert invoked[0].get("pact_key") == "PACT:mcp_server:build_success_result"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = McpServer(event_handler=handler)
        try:
            obj.create_server()
        except (TypeError, Exception):
            pass
        try:
            obj.run_server()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_review()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_trust()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_history()
        except (TypeError, Exception):
            pass
        try:
            obj.build_tool_error()
        except (TypeError, Exception):
            pass
        try:
            obj.build_success_result()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:mcp_server:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = McpServer()
        try:
            obj.create_server()
        except (TypeError, Exception):
            pass
        try:
            obj.run_server()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_review()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_trust()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_history()
        except (TypeError, Exception):
            pass
        try:
            obj.build_tool_error()
        except (TypeError, Exception):
            pass
        try:
            obj.build_success_result()
        except (TypeError, Exception):
            pass
