"""Emission compliance tests for cli (auto-generated by pact)."""

from cli.cli import Cli


class TestEmissionCompliance:
    """Verify cli emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_build_parser_emits_events(self):
        """Method build_parser emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.build_parser()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for build_parser'
        assert len(completed) >= 1, 'No completed/error event for build_parser'
        assert invoked[0].get("pact_key") == "PACT:cli:build_parser"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_parse_and_validate_args_emits_events(self):
        """Method parse_and_validate_args emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.parse_and_validate_args()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for parse_and_validate_args'
        assert len(completed) >= 1, 'No completed/error event for parse_and_validate_args'
        assert invoked[0].get("pact_key") == "PACT:cli:parse_and_validate_args"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_handle_review_emits_events(self):
        """Method handle_review emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.handle_review()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for handle_review'
        assert len(completed) >= 1, 'No completed/error event for handle_review'
        assert invoked[0].get("pact_key") == "PACT:cli:handle_review"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_handle_trust_emits_events(self):
        """Method handle_trust emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.handle_trust()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for handle_trust'
        assert len(completed) >= 1, 'No completed/error event for handle_trust'
        assert invoked[0].get("pact_key") == "PACT:cli:handle_trust"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_handle_history_emits_events(self):
        """Method handle_history emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.handle_history()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for handle_history'
        assert len(completed) >= 1, 'No completed/error event for handle_history'
        assert invoked[0].get("pact_key") == "PACT:cli:handle_history"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_handle_adopt_emits_events(self):
        """Method handle_adopt emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.handle_adopt()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for handle_adopt'
        assert len(completed) >= 1, 'No completed/error event for handle_adopt'
        assert invoked[0].get("pact_key") == "PACT:cli:handle_adopt"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_build_dispatch_table_emits_events(self):
        """Method build_dispatch_table emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.build_dispatch_table()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for build_dispatch_table'
        assert len(completed) >= 1, 'No completed/error event for build_dispatch_table'
        assert invoked[0].get("pact_key") == "PACT:cli:build_dispatch_table"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_map_decision_to_exit_code_emits_events(self):
        """Method map_decision_to_exit_code emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.map_decision_to_exit_code()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for map_decision_to_exit_code'
        assert len(completed) >= 1, 'No completed/error event for map_decision_to_exit_code'
        assert invoked[0].get("pact_key") == "PACT:cli:map_decision_to_exit_code"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_main_emits_events(self):
        """Method main emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.main()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for main'
        assert len(completed) >= 1, 'No completed/error event for main'
        assert invoked[0].get("pact_key") == "PACT:cli:main"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Cli(event_handler=handler)
        try:
            obj.build_parser()
        except (TypeError, Exception):
            pass
        try:
            obj.parse_and_validate_args()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_review()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_trust()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_history()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_adopt()
        except (TypeError, Exception):
            pass
        try:
            obj.build_dispatch_table()
        except (TypeError, Exception):
            pass
        try:
            obj.map_decision_to_exit_code()
        except (TypeError, Exception):
            pass
        try:
            obj.main()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:cli:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Cli()
        try:
            obj.build_parser()
        except (TypeError, Exception):
            pass
        try:
            obj.parse_and_validate_args()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_review()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_trust()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_history()
        except (TypeError, Exception):
            pass
        try:
            obj.handle_adopt()
        except (TypeError, Exception):
            pass
        try:
            obj.build_dispatch_table()
        except (TypeError, Exception):
            pass
        try:
            obj.map_decision_to_exit_code()
        except (TypeError, Exception):
            pass
        try:
            obj.main()
        except (TypeError, Exception):
            pass
