"""Emission compliance tests for reporter (auto-generated by pact)."""

from reporter.reporter import Reporter


class TestEmissionCompliance:
    """Verify reporter emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_canonicalize_emits_events(self):
        """Method canonicalize emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.canonicalize()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for canonicalize'
        assert len(completed) >= 1, 'No completed/error event for canonicalize'
        assert invoked[0].get("pact_key") == "PACT:reporter:canonicalize"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_seal_report_emits_events(self):
        """Method seal_report emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.seal_report()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for seal_report'
        assert len(completed) >= 1, 'No completed/error event for seal_report'
        assert invoked[0].get("pact_key") == "PACT:reporter:seal_report"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_verify_seal_emits_events(self):
        """Method verify_seal emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.verify_seal()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for verify_seal'
        assert len(completed) >= 1, 'No completed/error event for verify_seal'
        assert invoked[0].get("pact_key") == "PACT:reporter:verify_seal"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_format_report_emits_events(self):
        """Method format_report emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.format_report()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for format_report'
        assert len(completed) >= 1, 'No completed/error event for format_report'
        assert invoked[0].get("pact_key") == "PACT:reporter:format_report"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_render_json_emits_events(self):
        """Method render_json emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.render_json()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for render_json'
        assert len(completed) >= 1, 'No completed/error event for render_json'
        assert invoked[0].get("pact_key") == "PACT:reporter:render_json"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_render_markdown_emits_events(self):
        """Method render_markdown emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.render_markdown()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for render_markdown'
        assert len(completed) >= 1, 'No completed/error event for render_markdown'
        assert invoked[0].get("pact_key") == "PACT:reporter:render_markdown"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_render_github_emits_events(self):
        """Method render_github emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.render_github()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for render_github'
        assert len(completed) >= 1, 'No completed/error event for render_github'
        assert invoked[0].get("pact_key") == "PACT:reporter:render_github"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Reporter(event_handler=handler)
        try:
            obj.canonicalize()
        except (TypeError, Exception):
            pass
        try:
            obj.seal_report()
        except (TypeError, Exception):
            pass
        try:
            obj.verify_seal()
        except (TypeError, Exception):
            pass
        try:
            obj.format_report()
        except (TypeError, Exception):
            pass
        try:
            obj.render_json()
        except (TypeError, Exception):
            pass
        try:
            obj.render_markdown()
        except (TypeError, Exception):
            pass
        try:
            obj.render_github()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:reporter:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Reporter()
        try:
            obj.canonicalize()
        except (TypeError, Exception):
            pass
        try:
            obj.seal_report()
        except (TypeError, Exception):
            pass
        try:
            obj.verify_seal()
        except (TypeError, Exception):
            pass
        try:
            obj.format_report()
        except (TypeError, Exception):
            pass
        try:
            obj.render_json()
        except (TypeError, Exception):
            pass
        try:
            obj.render_markdown()
        except (TypeError, Exception):
            pass
        try:
            obj.render_github()
        except (TypeError, Exception):
            pass
