"""Emission compliance tests for schemas (auto-generated by pact)."""

from schemas.schemas import Schemas


class TestEmissionCompliance:
    """Verify schemas emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_severity_rank_emits_events(self):
        """Method severity_rank emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Schemas(event_handler=handler)
        try:
            obj.severity_rank()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for severity_rank'
        assert len(completed) >= 1, 'No completed/error event for severity_rank'
        assert invoked[0].get("pact_key") == "PACT:schemas:severity_rank"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_confidence_rank_emits_events(self):
        """Method confidence_rank emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Schemas(event_handler=handler)
        try:
            obj.confidence_rank()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for confidence_rank'
        assert len(completed) >= 1, 'No completed/error event for confidence_rank'
        assert invoked[0].get("pact_key") == "PACT:schemas:confidence_rank"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_learner_phase_rank_emits_events(self):
        """Method learner_phase_rank emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Schemas(event_handler=handler)
        try:
            obj.learner_phase_rank()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for learner_phase_rank'
        assert len(completed) >= 1, 'No completed/error event for learner_phase_rank'
        assert invoked[0].get("pact_key") == "PACT:schemas:learner_phase_rank"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_canonical_bytes_emits_events(self):
        """Method canonical_bytes emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Schemas(event_handler=handler)
        try:
            obj.canonical_bytes()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for canonical_bytes'
        assert len(completed) >= 1, 'No completed/error event for canonical_bytes'
        assert invoked[0].get("pact_key") == "PACT:schemas:canonical_bytes"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_canonical_hash_emits_events(self):
        """Method canonical_hash emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Schemas(event_handler=handler)
        try:
            obj.canonical_hash()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for canonical_hash'
        assert len(completed) >= 1, 'No completed/error event for canonical_hash'
        assert invoked[0].get("pact_key") == "PACT:schemas:canonical_hash"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_validate_iso_timestamp_emits_events(self):
        """Method validate_iso_timestamp emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Schemas(event_handler=handler)
        try:
            obj.validate_iso_timestamp()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for validate_iso_timestamp'
        assert len(completed) >= 1, 'No completed/error event for validate_iso_timestamp'
        assert invoked[0].get("pact_key") == "PACT:schemas:validate_iso_timestamp"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Schemas(event_handler=handler)
        try:
            obj.severity_rank()
        except (TypeError, Exception):
            pass
        try:
            obj.confidence_rank()
        except (TypeError, Exception):
            pass
        try:
            obj.learner_phase_rank()
        except (TypeError, Exception):
            pass
        try:
            obj.canonical_bytes()
        except (TypeError, Exception):
            pass
        try:
            obj.canonical_hash()
        except (TypeError, Exception):
            pass
        try:
            obj.validate_iso_timestamp()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:schemas:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Schemas()
        try:
            obj.severity_rank()
        except (TypeError, Exception):
            pass
        try:
            obj.confidence_rank()
        except (TypeError, Exception):
            pass
        try:
            obj.learner_phase_rank()
        except (TypeError, Exception):
            pass
        try:
            obj.canonical_bytes()
        except (TypeError, Exception):
            pass
        try:
            obj.canonical_hash()
        except (TypeError, Exception):
            pass
        try:
            obj.validate_iso_timestamp()
        except (TypeError, Exception):
            pass
