"""Emission compliance tests for intake (auto-generated by pact)."""

from intake.intake import Intake


class TestEmissionCompliance:
    """Verify intake emits structured events correctly."""

    def _make_handler(self):
        events = []
        return events, lambda event: events.append(event)

    def test_parse_diff_emits_events(self):
        """Method parse_diff emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Intake(event_handler=handler)
        try:
            obj.parse_diff()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for parse_diff'
        assert len(completed) >= 1, 'No completed/error event for parse_diff'
        assert invoked[0].get("pact_key") == "PACT:intake:parse_diff"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_classify_hunks_emits_events(self):
        """Method classify_hunks emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Intake(event_handler=handler)
        try:
            obj.classify_hunks()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for classify_hunks'
        assert len(completed) >= 1, 'No completed/error event for classify_hunks'
        assert invoked[0].get("pact_key") == "PACT:intake:classify_hunks"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_run_intake_emits_events(self):
        """Method run_intake emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Intake(event_handler=handler)
        try:
            obj.run_intake()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for run_intake'
        assert len(completed) >= 1, 'No completed/error event for run_intake'
        assert invoked[0].get("pact_key") == "PACT:intake:run_intake"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_generate_hunk_id_emits_events(self):
        """Method generate_hunk_id emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Intake(event_handler=handler)
        try:
            obj.generate_hunk_id()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for generate_hunk_id'
        assert len(completed) >= 1, 'No completed/error event for generate_hunk_id'
        assert invoked[0].get("pact_key") == "PACT:intake:generate_hunk_id"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_generate_request_id_emits_events(self):
        """Method generate_request_id emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Intake(event_handler=handler)
        try:
            obj.generate_request_id()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for generate_request_id'
        assert len(completed) >= 1, 'No completed/error event for generate_request_id'
        assert invoked[0].get("pact_key") == "PACT:intake:generate_request_id"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_detect_language_emits_events(self):
        """Method detect_language emits invoked and completed events."""
        events, handler = self._make_handler()
        obj = Intake(event_handler=handler)
        try:
            obj.detect_language()
        except (TypeError, Exception):
            pass
        invoked = [e for e in events if e.get("event") == "invoked"]
        completed = [e for e in events if e.get("event") in ("completed", "error")]
        assert len(invoked) >= 1, 'No invoked event for detect_language'
        assert len(completed) >= 1, 'No completed/error event for detect_language'
        assert invoked[0].get("pact_key") == "PACT:intake:detect_language"
        assert isinstance(invoked[0].get("input_classification"), list)

    def test_pact_key_format(self):
        """All emitted events have correctly formatted PACT keys."""
        events, handler = self._make_handler()
        obj = Intake(event_handler=handler)
        try:
            obj.parse_diff()
        except (TypeError, Exception):
            pass
        try:
            obj.classify_hunks()
        except (TypeError, Exception):
            pass
        try:
            obj.run_intake()
        except (TypeError, Exception):
            pass
        try:
            obj.generate_hunk_id()
        except (TypeError, Exception):
            pass
        try:
            obj.generate_request_id()
        except (TypeError, Exception):
            pass
        try:
            obj.detect_language()
        except (TypeError, Exception):
            pass
        for event in events:
            key = event.get("pact_key", "")
            assert key.startswith("PACT:intake:"), f"Bad pact_key: {key}"

    def test_null_handler_no_errors(self):
        """Component works without event_handler — no errors."""
        obj = Intake()
        try:
            obj.parse_diff()
        except (TypeError, Exception):
            pass
        try:
            obj.classify_hunks()
        except (TypeError, Exception):
            pass
        try:
            obj.run_intake()
        except (TypeError, Exception):
            pass
        try:
            obj.generate_hunk_id()
        except (TypeError, Exception):
            pass
        try:
            obj.generate_request_id()
        except (TypeError, Exception):
            pass
        try:
            obj.detect_language()
        except (TypeError, Exception):
            pass
