"""Diff Intake & Classification module."""
from intake.intake import (
    ClassificationLabel,
    ChroniclerEvent,
    ChroniclerEventType,
    DiffHunk,
    DiffSource,
    DiffSourceKind,
    EventEmitter,
    HunkMetadata,
    Intake,
    IntakeError,
    IntakePhase,
    IntakeResult,
    LedgerConfig,
    LedgerFieldRule,
    LineRange,
    ReviewRequest,
    ReviewStage,
    classify_hunks,
    detect_language,
    generate_hunk_id,
    generate_request_id,
    parse_diff,
    run_intake,
)
