"""Assessor component: Arbiter-style trust-weighted assessment merge."""
from assessor.assessor import (
    # Enums
    Severity,
    ReviewDecision,
    ReviewStage,
    Confidence,
    ChroniclerEventType,
    # Primitive types
    ReviewRequestId,
    ReviewerId,
    TrustWeight,
    ConfidenceScore,
    # Struct types
    FindingDeduplicationKey,
    Finding,
    TrustScore,
    Assessment,
    ConflictNote,
    PactAttribution,
    TesseraSeal,
    ChroniclerEvent,
    ReviewReport,
    MergeContext,
    SeverityScoreMap,
    ConfidenceScoreMap,
    # Constants
    PACT_COMPONENT,
    PACT_VERSION,
    DEFAULT_TRUST_WEIGHT,
    SEVERITY_SCORE,
    CONFIDENCE_MULTIPLIER,
    STAGE_PRIORITY,
    # Phase functions (standalone)
    _resolve_trust,
    _deduplicate_findings,
    _compute_decision,
    # Module-level convenience
    _build_report,
    merge_assessments,
    # Class
    Assessor,
)

__all__ = [
    "Severity",
    "ReviewDecision",
    "ReviewStage",
    "Confidence",
    "ChroniclerEventType",
    "ReviewRequestId",
    "ReviewerId",
    "TrustWeight",
    "ConfidenceScore",
    "FindingDeduplicationKey",
    "Finding",
    "TrustScore",
    "Assessment",
    "ConflictNote",
    "PactAttribution",
    "TesseraSeal",
    "ChroniclerEvent",
    "ReviewReport",
    "MergeContext",
    "SeverityScoreMap",
    "ConfidenceScoreMap",
    "PACT_COMPONENT",
    "PACT_VERSION",
    "DEFAULT_TRUST_WEIGHT",
    "SEVERITY_SCORE",
    "CONFIDENCE_MULTIPLIER",
    "STAGE_PRIORITY",
    "_resolve_trust",
    "_deduplicate_findings",
    "_compute_decision",
    "_build_report",
    "merge_assessments",
    "Assessor",
]
